use crate::config::ProviderConfig;

pub fn builtin_presets() -> Vec<ProviderConfig> {
    vec![
        ProviderConfig::new(
            "deepseek",
            "DeepSeek",
            "https://api.deepseek.com/v1",
            "DEEPSEEK_API_KEY",
            "deepseek-v4-pro",
            "deepseek-v4-pro",
            "responses",
        ),
        ProviderConfig::new(
            "qwen",
            "千问",
            "https://dashscope.aliyuncs.com/compatible-mode/v1",
            "DASHSCOPE_API_KEY",
            "qwen3.7-max",
            "qwen3.7-max",
            "responses",
        ),
        ProviderConfig::new(
            "zhipu",
            "智谱",
            "https://open.bigmodel.cn/api/paas/v4",
            "ZHIPU_API_KEY",
            "glm-5.1",
            "glm-5.1",
            "responses",
        ),
        ProviderConfig::new(
            "kimi",
            "Kimi",
            "https://api.moonshot.cn/v1",
            "MOONSHOT_API_KEY",
            "kimi-k2.6",
            "kimi-k2.6",
            "responses",
        ),
        ProviderConfig::new(
            "minimax",
            "Minimax",
            "https://api.minimaxi.com/v1",
            "MINIMAX_API_KEY",
            "minimax-m3",
            "MiniMax-M3",
            "responses",
        ),
        ProviderConfig::new(
            "mimo",
            "小米 MiMo",
            "https://api.xiaomimimo.com/v1",
            "MIMO_API_KEY",
            "mimo-v2.5-pro",
            "mimo-v2.5-pro",
            "responses",
        ),
        ProviderConfig::new(
            "custom",
            "中转站",
            "",
            "CUSTOM_API_KEY",
            "gpt-5.5",
            "gpt-5.5",
            "responses",
        ),
    ]
}
